table_list:
- id: Worker
  retain:
  - PAN
  columns:
  - id: AgencyWorker
    type: category
    unique_key: true
  - id: SWENo
    type: string
    unique_key: true
    degrade: hash_sha256
  - id: FTE
    type: numeric
    unique_key: true
  - id: PersonBirthDate
    type: date
    unique_key: true
  - id: GenderCurrent
    type: category
    unique_key: true
  - id: Ethnicity
    type: category
    unique_key: true
  - id: QualInst
    type: string
    unique_key: true
  - id: QualLevel
    type: category
    unique_key: true
  - id: StepUpGrad
    type: category
    unique_key: true
  - id: OrgRole
    type: category
    unique_key: true
  - id: RoleStartDate
    type: date
    unique_key: true
  - id: StartOrigin
    type: category
    unique_key: true
  - id: RoleEndDate
    type: date
    unique_key: true
  - id: LeaverDestination
    type: category
    unique_key: true
  - id: ReasonLeave
    type: category
    unique_key: true
  - id: FTE30
    type: numeric
    unique_key: true
  - id: Cases30
    type: numeric
    unique_key: true
  - id: WorkingDaysLost
    type: numeric
    unique_key: true
  - id: ContractWeeks
    type: numeric
    unique_key: true
  - id: FrontlineGrad
    type: category
    unique_key: true
  - id: Absat30Sept
    type: category
    unique_key: true
  - id: ReasonAbsence
    type: category
    unique_key: true
  - id: CFKSSstatus
    type: category
    unique_key: true
  - id: LA
    type: string
    unique_key: true
    enrich: la_name
  - id: Year
    type: numeric
    unique_key: true
    enrich: year
    sort: 0
- id: LA_Level
  retain:
  - PAN
  columns:
  - id: NumberOfVacancies
    type: numeric
    unique_key: true
  - id: NoAgencyFTE
    type: numeric
  - id: NoAgencyHeadcount
    type: numeric
    unique_key: true
  - id: LA
    type: string
    enrich: la_name
  - id: Year
    type: numeric
    unique_key: true
    enrich: year
    sort: 0