import pandas as pd
data = pd.DataFrame(
        {
            "DEC": [
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                "2016-08-31",
                None,
            ],
            "Has_next_episode": [
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                False,
            ],
            "DECOM": [
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
                "2016-08-22",
            ],
            "DECOM_next": [
                "2016-11-22",
                "2016-11-22",
                "2016-11-22",
                "2016-11-22",
                "2016-11-22",
                "2016-11-22",
                "2016-11-22",
                "2016-11-22",
                "2016-11-22",
                "2016-11-22",
                None,
            ],
            "RNE": ["P", "P", "P", "P", "P", "P", "P", None, "P", "P", "P"],
            "RNE_next": ["P", "DIFF", "P", "P", "P", "P", "P", None, None, "P", None],
            "LS": ["C2", "C2", "C2", "C2", "C2", "C2", "C2", None, "C2", "C2", "C2"],
            "LS_next": [
                "C2",
                "C2",
                "DIFF",
                "C2",
                "C2",
                "C2",
                "C2",
                None,
                None,
                "C2",
                None,
            ],
            "PLACE": ["U1", "U1", "U1", "U1", "U1", "U1", "U1", None, "U1", "U1", "U1"],
            "PLACE_next": [
                "U1",
                "U1",
                "U1",
                "DIFF",
                "U1",
                "U1",
                "U1",
                None,
                None,
                "U1",
                None,
            ],
            "PLACE_PROVIDER": [
                "PR1",
                "PR1",
                "PR1",
                "PR1",
                "PR1",
                "PR1",
                "PR1",
                None,
                "PR1",
                "PR1",
                "PR1",
            ],
            "PLACE_PROVIDER_next": [
                "PR1",
                "PR1",
                "PR1",
                "PR1",
                "DIFF",
                "PR1",
                "PR1",
                None,
                None,
                "PR1",
                None,
            ],
            "PL_POST": [
                "ABC1",
                "ABC1",
                "ABC1",
                "ABC1",
                "ABC1",
                "ABC1",
                "ABC1",
                None,
                "ABC1",
                "ABC1",
                "ABC1",
            ],
            "PL_POST_next": [
                "ABC1",
                "ABC1",
                "ABC1",
                "ABC1",
                "ABC1",
                "DIFF",
                "ABC1",
                None,
                None,
                "ABC1",
                None,
            ],
            "URN": [
                "SC1234",
                "SC1234",
                "SC1234",
                "SC1234",
                "SC1234",
                "SC1234",
                "SC1234",
                None,
                "SC1234",
                "SC1234",
                "SC1234",
            ],
            "URN_next": [
                "SC1234",
                "SC1234",
                "SC1234",
                "SC1234",
                "SC1234",
                "SC1234",
                "DIFF",
                None,
                None,
                "SC1234",
                None,
            ],
        }
    )

for index, row in data.iterrows():
    print(f"\ndef test__is_next_episode_duplicate_():")
    print(f"    data = pd.DataFrame (\n        {{")
    for column, value in row.items():
        print(f'            "{column}": [{value}],')
    print("        }\n    )")
    print(f'    data["Test result"] = _is_next_episode_duplicate(data)')
    print(f'    assert data["Test result"].tolist() == []')
