table_list:
- id: AD1
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: DOB
    type: date
    degrade: first_of_month
  - id: DATE_INT
    type: date
    unique_key: true
  - id: DATE_MATCH
    type: date
    unique_key: true
  - id: FOSTER_CARE
    type: category
  - id: NB_ADOPTR
    type: integer
  - id: SEX_ADOPTR
    type: category
  - id: LS_ADOPTR
    type: category
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
    sort: 0
- id: Episodes
  retain:
  - PAN
  - SUFFICIENCY
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: DECOM
    type: date
    unique_key: true
  - id: RNE
    type: category
  - id: LS
    type: category
  - id: CIN
    type: category
  - id: PLACE
    type: category
  - id: PLACE_PROVIDER
    type: category
  - id: DEC
    type: date
    sort: 0
  - id: REC
    type: category
  - id: REASON_PLACE_CHANGE
    type: category
  - id: HOME_POST
    type: postcode
    degrade: short_postcode
  - id: PL_POST
    type: postcode
    degrade: short_postcode
  - id: URN
    type: string
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
    sort: 1
- id: Header
  retain:
  - PAN
  - SUFFICIENCY
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: SEX
    type: category
  - id: DOB
    type: date
    degrade: first_of_month
  - id: ETHNIC
    type: category
  - id: UPN
    type: string
    exclude:
    - SUFFICIENCY
  - id: MOTHER
    type: category
    exclude:
    - SUFFICIENCY
  - id: MC_DOB
    type: date
    degrade: first_of_month
    exclude:
    - SUFFICIENCY
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
    sort: 1
- id: Missing
  retain:
  - PAN
  - SUFFICIENCY
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: DOB
    type: date
    degrade: first_of_month
  - id: MISSING
    type: category
    unique_key: true
  - id: MIS_START
    type: date
    unique_key: true
  - id: MIS_END
    type: date
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
    sort: 0
- id: OC2
  retain:
  - PAN
  - SUFFICIENCY
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: DOB
    type: date
    unique_key: true
    degrade: first_of_month
  - id: SDQ_SCORE
    type: integer
    unique_key: true
  - id: SDQ_REASON
    type: category
    unique_key: true
  - id: CONVICTED
    type: category
    unique_key: true
  - id: HEALTH_CHECK
    type: category
    unique_key: true
    exclude:
    - SUFFICIENCY
  - id: IMMUNISATIONS
    type: category
    unique_key: true
    exclude:
    - SUFFICIENCY
  - id: TEETH_CHECK
    type: category
    unique_key: true
    exclude:
    - SUFFICIENCY
  - id: HEALTH_ASSESSMENT
    type: category
    unique_key: true
    exclude:
    - SUFFICIENCY
  - id: SUBSTANCE_MISUSE
    type: category
    unique_key: true
  - id: INTERVENTION_RECEIVED
    type: category
    unique_key: true
  - id: INTERVENTION_OFFERED
    type: category
    unique_key: true
  - id: LA
    type: string
    unique_key: true
    enrich: la_name
  - id: YEAR
    type: integer
    unique_key: true
    enrich: year
    sort: 0
- id: OC3
  retain:
  - PAN
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: DOB
    type: date
    unique_key: true
    degrade: first_of_month
  - id: IN_TOUCH
    type: category
    unique_key: true
  - id: ACTIV
    type: category
    unique_key: true
  - id: ACCOM
    type: category
    unique_key: true
  - id: LA
    type: string
    unique_key: true
    enrich: la_name
  - id: YEAR
    type: integer
    unique_key: true
    enrich: year
    sort: 0
- id: PlacedAdoption
  columns:
  - id: CHILD
    type: string
    enrich: add_la_suffix
  - id: DOB
    type: date
    degrade: first_of_month
  - id: DATE_PLACED
    type: date
    unique_key: true
  - id: DATE_PLACED_CEASED
    type: date
    unique_key: true
  - id: REASON_PLACED_CEASED
    type: category
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
    sort: 0
- id: PrevPerm
  retain:
  - PAN
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: DOB
    type: date
    degrade: first_of_month
  - id: PREV_PERM
    type: category
  - id: LA_PERM
    type: string
  - id: DATE_PERM
    type: date
    unique_key: true
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
    sort: 0
- id: Reviews
  retain:
  - PAN
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: DOB
    type: date
    degrade: first_of_month
  - id: REVIEW
    type: date
    unique_key: true
  - id: REVIEW_CODE
    type: category
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
    sort: 0
- id: UASC
  retain:
  - PAN
  - SUFFICIENCY
  columns:
  - id: CHILD
    type: string
    unique_key: true
    enrich: add_la_suffix
  - id: DOB
    type: date
    degrade: first_of_month
  - id: SEX
    type: category
  - id: DUC
    type: date
    sort: 0
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
    sort: 1
- id: SocialWorker
  columns:
  - id: CHILD
    type: string
    enrich: add_la_suffix
  - id: DOB
    type: date
    degrade: first_of_month
  - id: SW_ID
    type: string
  - id: SW_DECOM
    type: date
  - id: SW_DEC
    type: date
  - id: SW_REASON
    type: category
  - id: LA
    type: string
    enrich: la_name
  - id: YEAR
    type: integer
    enrich: year
